OPENAI_API_KEY="#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"
[google]
client_id = "1086275699426-6p8s8lm09f87cibougvpq23bnb78murt.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"
